### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/jiff-cron#13]
@LeoniePhiline if you're amenable, would you be okay to add yourself to the [authors field](https://github.com/maxcountryman/jiff-cron/blob/8dd5f0e5971ec5ef115f32bfaa457a323cdc7428/Cargo.toml#L4-L7) in the Cargo.toml?

It's totally up to you, but if you don't mind I'd feel better with you being included directly.

On that note if we want to move this repo into a shared org, I'd be happy to transfer it so we can share full ownership.

**Comment by LeoniePhiline** [comment]
Do you have any inclination as it comes to the sorting of authors?

My name would put me first, in alphabetical order. However, as you started the fork I would set you first. What's your take?

**Comment by LeoniePhiline** [comment]
> On that note if we want to move this repo into a shared org, I'd be happy to transfer it so we can share full ownership.

I think that's a great idea.

**Comment by maxcountryman** [comment]
Alphabetical is fine by me.

**Comment by maxcountryman** [comment]
> > On that note if we want to move this repo into a shared org, I'd be happy to transfer it so we can share full ownership.
> 
> I think that's a great idea.

Cool. Any idea for what to call such an org? I think it's as simple as picking a name (that's available), adding us both as owners, and then transferring the repo.

**Comment by LeoniePhiline** [comment]
> Any idea for what to call such an org?

For the moment, the crate's name might suffice. Would you prefer a "more proper" name?

**Comment by maxcountryman** [comment]
> > Any idea for what to call such an org?
> 
> For the moment, the crate's name might suffice. Would you prefer a "more proper" name?

That makes sense to me. We could always make it more general later if there's a reason to.

**Comment by LeoniePhiline** [comment]
Resolved by #14.
