### ISSUE TITLE
Reconfigure the repository for `Rebase and merge` PR strategy?

### ISSUE THREAD

**Issue by LeoniePhiline** [maxcountryman/jiff-cron#15]
GitHub defaults to these merge commits:

![image](https://github.com/user-attachments/assets/615626e3-647e-4ff8-98d5-daef828144ec)

As a proponent of clean history and fully or mostly rebase-based approaches, I think we might benefit from keeping history and commit subjects intact by only allowing the third option:

![image](https://github.com/user-attachments/assets/84cc8577-c7ca-4d29-a4ab-a1a90c04d527)

IIRC that's a repository-level setting.

 I do not feel very strongly about this in an open source context, and I will not insist. :)

**Comment by maxcountryman** [comment]
That makes sense to me. I'm guilty of squashing PRs where the intermediary commits are noisier (fixing CI, etc). So sometimes I use squash as my personal default. I agree that rebase and merge is usually the best fit for maintaining a proper git history.

**Comment by LeoniePhiline** [comment]
> I'm guilty of squashing PRs where the intermediary commits are noisier (fixing CI, etc). So sometimes I use squash as my personal default.

If that is what you would like to keep using, I'll be fine with that.

Collaboration is more important than any kind of perfectionism, and pragmatism is often a good choice.

**Comment by maxcountryman** [comment]
I don't need to impose my habits on folks or this repo: if you prefer to use rebase and merge and set that as the standard for this repo we should do that.

**Comment by LeoniePhiline** [comment]
The huge advantage of using a rebase strategy is that the pull request CI will check the code in a state as if it was already merged.

We can and should require that PRs are up to date with the `main` branch, and new commits are only ever seated on top of `main`'s `HEAD`.

```
A-B-C-D    ->  A-B-C-D-E
       \E 
```

`E` is tested before the merge and becomes `main`'s `HEAD` after rebase. 

Common merge strategies verify that `main` and the PR's branch are compatible only *after* merge, when CI is run on `main`.

```
A-B-C-D  ->  A-B-C-D-F
     \E           \E/
```

`F` combines `D` and `E` and has not been tested in combination before the merge.

Rebase strategies also allow to preserve the detail of larger multi step changesets that have been split into a number of commits containing logically grouped modifications.

My reasoning here is that code is not necessarily reviewed only before the initial merge: also later it should be possible to retrace the reasoning of implementation of bigger changes.

**Comment by maxcountryman** [comment]
That seems like sound reasoning to me. 😁

**Comment by LeoniePhiline** [comment]
I'll try to configure this correctly. Let's try with #20 and adjust if needed.

**Comment by LeoniePhiline** [comment]
Set up in:

- https://github.com/jiff-cron/jiff-cron/settings#merge-button-settings
- https://github.com/jiff-cron/jiff-cron/settings/branch_protection_rules/56408338

https://github.com/jiff-cron/jiff-cron/pull/20 now requires to be up to date with `main`, requires your review, requires all conversations to be resolved, and only allows rebase.

I would not mind enabling a signed commits requirement, too, but that might be quite detrimental to community contributions.

**Comment by LeoniePhiline** [comment]
Closing as done. Let's re-open and discuss if issues with this configuration occur.
