### ISSUE TITLE
Renovate or Dependabot integration?

### ISSUE THREAD

**Issue by LeoniePhiline** [maxcountryman/jiff-cron#21]
Follow up from #18.

I had been wondering if we should set up renovate-bot to propose upgrades when new breaking dependency versions are released.

We have few dependencies, no lock file, and thus only semver-breaking changes are relevant to us.

Integrating with renovate would provide us with an automatically managed dependency dashboard, listing available major updates.

It would also provide us with automated PR generation (if enabled), which is a handy way of ensuring we get notified as one of our dependencies gets outdated.

**Comment by maxcountryman** [comment]
Here's [a comparison](https://docs.renovatebot.com/bot-comparison/) (on renovate-bot's site) of renovate-bot versus dependabot.

It's not clear to me one is certainly better than the other but at the same time there are things renovate-bot does that dependabot doesn't so that may be reason enough to choose it.

**Comment by LeoniePhiline** [comment]
I have experience with renovate-bot only, that's why it was my go-to.

An example of what a dependency dashboard: https://github.com/LeoniePhiline/async-mailer/issues/13
and the configuration in use: https://github.com/LeoniePhiline/async-mailer/blob/main/renovate.json

If dependabot works well for you, then I'm happy to go that way, too!

I assume both are fine - our requirements are very limited.

**Comment by maxcountryman** [comment]
If you like renovate-bot then let's go ahead with that.

**Comment by LeoniePhiline** [comment]
I have requested access for the Renovate GitHub App to the `jiff-cron` organization:

![image](https://github.com/user-attachments/assets/f412d0d6-2dc1-4bdc-b32d-9882b833a635)

However I do not seem to have the permissions to accept the request.

![image](https://github.com/user-attachments/assets/b5c37432-2974-4e3c-871e-03a2dc80e0ee)

Could you have a look if you can see that as organization owner?

**Comment by maxcountryman** [comment]
Sorry about that! I'd like to make you an org owner, but it seems "Admin" is the only option? (I did also approve the request to add Renovate just now.)

<img width="1608" alt="Screenshot 2024-11-15 at 11 10 07" src="https://github.com/user-attachments/assets/377949b7-5ef5-4b27-9036-655d719bf8f4">

**Comment by maxcountryman** [comment]
I think I was able to do so now. Please let me know if this doesn't work.

<img width="1608" alt="Screenshot 2024-11-15 at 11 15 33" src="https://github.com/user-attachments/assets/647f07a8-717b-413f-8fed-69b6008d1359">

**Comment by LeoniePhiline** [comment]
Renovate is set up with default configuration.

Logs can be inspected at https://developer.mend.io/github/jiff-cron/jiff-cron.

I am closing this as completed. If any fine tuning of renovate's configuration should be required, then let's open new issues for that.

**Comment by LeoniePhiline** [comment]
PS: Possible fine tuning of renovate-bot not only includes dep semver range and dependency pinning strategies, but also e.g. labels to be applied to MRs automatically, or automatic MR reviewer assignments.
