### ISSUE TITLE
Shall we redefine `Schedule` equality?

### ISSUE THREAD

**Issue by LeoniePhiline** [maxcountryman/jiff-cron#9]
Currently, `impl PartialEq for Schedule` compares the source string.

However, this may fail for `Schedule`s I would find _equal_, but whose source strings contain white space differences.

I.e. I would like this test to pass:

```rust
    use eyre::Result;
    use jiff_cron::Schedule as CronSchedule;
    
    use super::Schedule; // Just a struct - see `assert_eq!` below.
    
    #[test]
    fn cron_schedule_deserialize_smoke_test() -> Result<()> {
        // Deserialize a `Schedule` from YAML.
        let schedule = serde_yaml::from_str::<Schedule>(indoc! {r#"
            # Every second.
            #      sec  min   hour   day of month   month   day of week   year
            when: "*    *     *      *              *       *             *"
            path: foo/bar
        "#})?;

        // Equality is based on parsed fields, excluding `source`,
        // which may (and does here) contain contain whitespace differences.
        assert_eq!(
            schedule,
            Schedule {
                when: CronSchedule::from_str("* * * * * * *")?,
                path: Some(PathBuf::from("foo/bar")),
            }
        );

        Ok(())
    }
```

The equality check is performed with a schedule which, to my mind, is equal to the one deserialized. However, we do not normalize source representations and store `"*    *     *      *              *       *             *"` as `jiff_cron::Schedule::source`.

I propose to compare fields instead:

I.e. to implement `PartialEq` for `Schedule` in terms of [`jiff_cron::Schedule::timeunitspec_eq`](https://docs.rs/jiff-cron/latest/jiff_cron/struct.Schedule.html#method.timeunitspec_eq).

**Comment by LeoniePhiline** [comment]
The original implementation at https://github.com/zslayton/cron/commit/7752df70ad34933c2e98a5d5082cd0b7bf990450 describes the source comparison approach as _"a holistic definition of equality"_.

I disagree with that notion. To my mind, comparing the parsed representation is more correct, while taking whitespace into account does not add value.

As `Schedule::source()` is exposed since my recent change at https://github.com/maxcountryman/jiff-cron/commit/c5d5589936aef5c6bca17f0c86030e7a98a8dc42#diff-dce650093f94ff40ea28c13f363195e6968eeb17883f90a4d3cac98958fbe453R363-R366, users still have the option to compare source strings.

**Comment by maxcountryman** [comment]
I agree with your assessment.

**Comment by LeoniePhiline** [comment]
resolved by https://github.com/maxcountryman/jiff-cron/pull/10
